export const DRAGON = {
    FETCH: 'DRAGON_FETCH',
    FETCH_ERROR: 'DRAGON_FETCH_ERROR',
    FETCH_SUCCESS: 'DRAGON_FETCH_SUCCESS',
}

export const PUBLIC_DRAGON = {
    FETCH: 'PUBLIC_DRAGON_FETCH',
    FETCH_ERROR: 'PUBLIC_DRAGON_FETCH_ERROR',
    FETCH_SUCCESS: 'PUBLIC_DRAGON_FETCH_SUCCESS',
}